# Generated by Django 5.1 on 2024-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('remote_ip', models.GenericIPAddressField()),
                ('remote_user', models.CharField(blank=True, default='', max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('response', models.PositiveIntegerField()),
                ('bytes', models.PositiveIntegerField()),
                ('referrer', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nginx Log',
                'verbose_name_plural': 'Nginx logs',
                'ordering': ['-time'],
            },
        ),
    ]
